apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deploy
spec:
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
      - name: expiration
        image: jatinbumbra/expiration
        env:
          - name: NATS_URL
            value: 'http://nats-service:4222'
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: REDIS_HOST
            value: expiration-redis-service